### ISSUE TITLE
老哥似乎有bug

### ISSUE THREAD

**Issue by ohMyJason** [astwyg/mask_watcher#3]
python watcher.py
Traceback (most recent call last):
  File "watcher.py", line 3, in <module>
    from log.logger import logger as log
ModuleNotFoundError: No module named 'log'

**Comment by ming076** [comment]
'log'是程序自己写的模块，我是用这个方法import进去的。
Python导入自己写的模块
https://blog.csdn.net/kelvinLLL/article/details/65631647

**Comment by ohMyJason** [comment]
> 'log'是程序自己写的模块，我是用这个方法import进去的。
> Python导入自己写的模块
> https://blog.csdn.net/kelvinLLL/article/details/65631647

感谢，我python不太熟，我查看了一下源码。似乎是通过搜索html代码中的keyword来判断是否有货的，我尝试使用java实现了一下，发现京东商城获取的html没有 无货 字样。似乎是通过js渲染的。这个问题您是怎么解决的呢。

**Comment by ming076** [comment]
它是用了一个Python模块，selenium里面的webdriver来读取页面的信息的，具体细节我也不太清楚。

**Comment by astwyg** [comment]
@ohMyJason 
你需要将项目目录加入PATH, log是自己写的模块.
如果你用java重写, 需要整个页面js都执行完, 才能找到关键字.
