### ISSUE TITLE
一些bug（windows环境）

### ISSUE THREAD

**Issue by Tiacx** [astwyg/mask_watcher#5]
1）watcher.py 要提到根目录来
2）log目录下要建一个logs文件夹
3）需要下载 chromedirver.exe，并配置环境变量
传送门：https://sites.google.com/a/chromium.org/chromedriver/home
4）watcher.py 第42行，chromedriver.exe 的路径直接写 “chromedriver.exe” 就行（先配置环境变量）
5）watcher.py 第31行，shop.json 的路径不要“..”

**Comment by ming076** [comment]
还有一个小bug，
watcher.py 第37行，info.get("keyword")应该改成info.get("key_word")；

有个小疑问，我这边运行，同一个网址会跑好几次，不知道是哪里的原因。

INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
INFO: checking https://item.jd.com/1238056920.html / 无货,下柜

**Comment by Tiacx** [comment]
这得问作者大大了🤣

**Comment by Tiacx** [comment]
> 还有一个小bug，
> watcher.py 第37行，info.get("keyword")应该改成info.get("key_word")；
> 
> 有个小疑问，我这边运行，同一个网址会跑好几次，不知道是哪里的原因。
> 
> INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
> INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
> INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
> INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
> INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
> INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
> INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
> INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
> INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
> INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
> INFO: checking https://item.jd.com/65399049577.html / 无货,下柜
> INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
> INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
> INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
> INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
> INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
> INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
> INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
> INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
> INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
> INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
> INFO: checking https://item.jd.com/34197525576.html / 无货,下柜
> INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
> INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
> INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
> INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
> INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
> INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
> INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
> INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
> INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
> INFO: checking https://item.jd.com/1238056920.html / 无货,下柜
> INFO: checking https://item.jd.com/1238056920.html / 无货,下柜

这得问作者大大了🤣

**Comment by ming076** [comment]
我对比了下，好像是我用Spyder打开运行的问题，虽然原因不明，但是目前在cmd下运行没有问题。
我是windows10的环境。

如果能更新一下店铺清单就更好了。

**Comment by astwyg** [comment]
@Tiacx 
请将项目根目录加入PATH, 可解决绝大部分问题, 关于chromedirver你是对的, 需要根据自己的操作系统选择合适的下载.

@ming076 
欢迎贡献: https://github.com/astwyg/mask_watcher/blob/master/config/shop.json
